services:
  app:
    build: .
    container_name: app-laravel
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - laravel_web:/var/www
    environment:
      - SERVICE_NAME=app-laravel
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

    networks:
      - app-network
    secrets:
      - source: app-file
        target : /var/www/.env
    tty: true
  db:
    image: mysql:8
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=hostlab
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - SERVICE_NAME=mysql
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    volumes:
      - laravel_web:/var/www
      - type: bind
        source: ./nginx/conf.d
        target: /etc/nginx/conf.d
        read_only: true
    tty: true
    ports:
      - "8080:80"
    networks:
      - app-network
    depends_on:
      - app

#Docker Networks
networks:
  app-network:
    driver: bridge

volumes:
  laravel_web:
  db_data:

secrets:
  app-file:
    file: /home/haroldhang/app_env.txt

